navigation:
  - title: Scrum Lake
    url: /
  - title: Scrum Lake Story
    url: /thestory
  - title: Your Facilitators
    url: /divemasters
  - title: Upcoming Workshops
    url: /workshops

legal:
  - title: Privacy Policy
    url: /legal/privacy
  - title: Terms and Conditions
    url: /legal/terms
  - title: Copyright, Licenses and Disclaimer
    url: /legal/agreements

workshops:
  - eventidchk: id/584261/chk/17d3
#  - eventidchk: id/586866/chk/8941
#  - eventidchk: id/586867/chk/c8a0
