navigation:
  - title: Scrum Lake
    url: /
  - title: Scrum Lake Story
    url: /thestory
  - title: Your Facilitators
    url: /divemasters
  - title: Upcoming Workshops
    url: /workshops

legal:
  - title: Privacy Policy
    url: /legal/privacy
  - title: Terms and Conditions
    url: /legal/terms
  - title: Copyright, Licenses and Disclaimer
    url: /legal/agreements

workshops:
  - title: Scrum Lake Bedrock
    uri: https://www.eventbrite.co.uk/e/scrum-lake-artefacts-tickets-130047933871
    price: $40
    startdatetime: 6 February 2020 at 20:00
    enddatetime: 28 February 2020 at 22:00
    bullets: ['Interactive','Co-Creative','Workshop']
    eventimage: bedrock

  - title: Scrum Lake Artefacts 
    uri: https://www.eventbrite.co.uk/e/scrum-lake-artefacts-tickets-130047933871
    price: $65
    startdatetime: 20 February 2020 at 20:00
    enddatetime: 20 February 2020 at 22:00
    bullets: ['Interactive','Co-Creative','Workshop']
    eventimage: artefacts 

  - title: Scrum Lake Introduction
    uri: https://www.eventbrite.co.uk/e/scrum-lake-artefacts-tickets-130047933871
    price: Free
    startdatetime: 28 November 2020 at 20:00
    enddatetime: 28 November 2020 at 22:00
    bullets: ['Free Introduction','Presentation','What you can expect']
    eventimage: introduction