navigation:
  - title: Scrum Lake
    url: /
  - title: Scrum Lake Story
    url: /thestory
  - title: Your Facilitators
    url: /divemasters
  - title: Upcoming Workshops
    url: /workshops

legal:
  - title: Privacy Policy
    url: /legal/privacy
  - title: Terms and Conditions
    url: /legal/terms
  - title: Copyright, Licenses and Disclaimer
    url: /legal/agreements

workshops:
  - title: What is Scrum Lake?
    uri: https://www.eventbrite.co.uk/e/scrum-lake-artefacts-tickets-130047933871
    price: Free
    startdatetime: 30 January 2020 at 20:00
    enddatetime: 28 January 2020 at 20:30
    list: ['Free Introduction','Short Presentation','Our Approach']
    eventimage: introduction

  - title: Scrum Values
    uri: https://www.eventbrite.co.uk/e/scrum-lake-artefacts-tickets-130047933871
    price: £40
    startdatetime: 6 February 2020 at 20:00
    enddatetime: 6 February 2020 at 22:00
    list: ['Interactive','Co-Creative','Workshop']
    eventimage: theoryandvalues

  - title: Scrum Theory and Values
    uri: https://www.eventbrite.co.uk/e/scrum-lake-artefacts-tickets-130047933871
    price: £70
    startdatetime: 28 November 2020 at 20:00
    enddatetime: 28 November 2020 at 22:00
    list: ['Interactive','Co-Creative','Workshop']
    eventimage: theoryandvalues